version: 2


jobs:
  build:
    docker:
      - image: circleci/dart:latest
    steps:
      - checkout
      - run: dart pub get
      - run:
          name: Run server.dart
          command: dart bin/server.dart